layout: "main"
#logger: "console"
appname: "Saml2Test"
charset: "UTF-8"
template: "template_toolkit"
issuer: "https://netsaml2-testapp.local"
url: "https://netsaml2-testapp.local"
cert: "sign-certonly.pem"
encryption_key: "sign-private.pem"
key: "sign-private.pem"
slo_url_soap: "/slo-soap"
slo_url_redirect: "/sls-redirect-response"
slo_url_post: "/sls-post-response"
acs_url_post: "/consumer-post"
acs_url_artifact: "/consumer-artifact"
org_name: "Net::SAML2 Saml2Test"
org_display_name: "Saml2Test app for Net::SAML2"
org_contact: "saml2test@example.com"
error_url: "/error"
force_authn: 1
is_passive: 0
sign_metadata: 1
authnreq_signed: 1
ssl_verify_hostname: 0
acs_url_in_request: 1
