layout: "main"
#logger: "console"
appname: "Saml2Test"

idp: "http://localhost:8880/metadata.xml"
issuer: "https://netsaml2-testapp.local"
url: "https://netsaml2-testapp.local"
cert: "sign-certonly.pem"
key: "sign-nopw-cert.pem"
cacert: "saml_cacert.pem"
