---
name: shared-workflow

on:
  workflow_call:
    inputs:
      perl-version:
        required: true
        type: string
      coverage:
        required: false
        type: string


jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: perl:${{ inputs.perl-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Net::SAML2 Depends
        run: |
          apt-get install libxml2 make gcc wget;
          cpanm Module::Pluggable
          cpanm App::cpm;
          # Sub::Name has test that fail every so many times on t/lexical.t
          # we ignore these test failures for now...
          cpm install -g --show-build-log-on-failure Sub::Name;
          cpm install -g --test --show-build-log-on-failure --cpanfile cpanfile;
      - name: Build Module
        run: |
          perl Makefile.PL;
          make
      - name: Run tests
        if: ${{ !inputs.coverage  }}
        run: |
          prove -lr -l -b -I inc t
      - name: Run tests including coverage
        if: ${{ inputs.coverage  }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PERL_SERVICE_NAME: github-actions
        run: |
          cpm install -g Devel::Cover::Report::Coveralls
          cover -test -report Coveralls
